version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yadegar_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /root/services/cdn/yaadegaar/public:/var/www/cdn/public
    networks:
      - shared_net
    
  web:
    image: nginx:alpine
    container_name: yadegar_machine
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/services/cdn/yaadegaar/public:/var/www/cdn/public
    networks:
      - shared_net

networks:
  shared_net:
    external: true
