server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    # Handle Laravel routes
    location / {
        try_files $uri $uri/ /index.php?$query_string;

    }

    # PHP-FPM settings
    location ~ \.php$ {
        fastcgi_pass yadegar_app:9000; # `yadegar_app` is your PHP container's service name
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Disable access to hidden files
    location ~ /\. {
        deny all;
    }
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

}
