[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
pidfile=/var/run/supervisord.pid
nodaemon=false
silent=false

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:octane]
# command=php artisan octane:start --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=8000
command=php -d variables_order=EGPCS artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080
directory=/var/www/html
autostart=true
autorestart=true
stderr_logfile=/var/log/octane.err.log
stdout_logfile=/var/log/octane.out.log
user=www-data



